export const SESSION_IDLE_TIMEOUT_CODE = 'SESSION_IDLE_TIMEOUT';
export const SESSION_TIMEOUT_REASON = 'session-timeout';
export const SESSION_TIMEOUT_REASON_QUERY_PARAM = 'reason';
export const SESSION_IDLE_TIMEOUT_MINUTES = 15;
export const SESSION_IDLE_TIMEOUT_MS = SESSION_IDLE_TIMEOUT_MINUTES * 60 * 1000;
